# Generated by Django 4.2.3 on 2023-07-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('payment_method', models.CharField(max_length=32)),
                ('date', models.DateField()),
                ('receipt', models.TextField()),
                ('status', models.CharField(max_length=32)),
                ('order', models.TextField()),
            ],
        ),
    ]
