# Generated by Django 4.2.3 on 2023-07-11 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0003_rename_password_salesperson_store_numb_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='salesperson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vendor.salesperson'),
            preserve_default=False,
        ),
    ]
