# Generated by Django 4.2.3 on 2023-07-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_salesperson'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='products',
            field=models.ManyToManyField(to='inventory.product'),
        ),
    ]
