# Generated by Django 4.2.3 on 2023-07-11 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_salesperson'),
        ('customer', '0002_buyer_user'),
        ('cart', '0002_basket_products'),
        ('payment', '0002_remove_payment_management_order_and_more'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place_order',
            name='cart',
            field=models.ManyToManyField(to='cart.basket'),
        ),
        migrations.AddField(
            model_name='place_order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.buyer'),
        ),
        migrations.AddField(
            model_name='place_order',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.payment_management'),
        ),
        migrations.AddField(
            model_name='place_order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
    ]
